-- LunaTicK Phase B: canonical Supabase schema
--
-- Approved design:
--   * profiles.auth_subject is the immutable Auth0 subject and primary key.
--   * user_hash is legacy, non-unique, and never used for authorization.
--   * The Streamlit server owns all initial data access using a service-role key.
--   * Browser roles receive no direct table privileges in this first migration.
--
-- This migration creates an empty schema only. It imports no SQLite records.

begin;

-- Canonical profile and identity record.
create table public.profiles (
    auth_subject text constraint idx_profiles_auth_subject primary key,
    user_hash text,
    username text not null,
    display_name text not null default 'Moon Wanderer',
    avatar text not null default '🌙',
    bio text not null default '',
    email text,
    birth_date text,
    birth_time text,
    birth_place text,
    lat double precision,
    lon double precision,
    utc_offset double precision,
    hd_profile text,
    hd_authority text,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    constraint profiles_username_format check (username = lower(username) and username ~ '^[a-z0-9_]{3,24}$'),
    constraint profiles_display_name_length check (char_length(display_name) between 1 and 48),
    constraint profiles_bio_length check (char_length(bio) <= 240)
);

-- Private reflection data.
create table public.journal_entries (
    id bigint generated by default as identity primary key,
    profile_auth_subject text not null references public.profiles(auth_subject) on delete cascade,
    phase text not null,
    prompt_type text not null,
    content text not null,
    created_at timestamptz not null default timezone('utc', now())
);

-- Shared Community catalog and board discussion.
create table public.boards (
    slug text primary key,
    name text not null,
    description text not null default '',
    created_at timestamptz not null default timezone('utc', now())
);

create table public.board_posts (
    id bigint generated by default as identity primary key,
    board_slug text not null references public.boards(slug) on delete restrict,
    profile_auth_subject text not null references public.profiles(auth_subject) on delete cascade,
    title text not null,
    content text not null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    is_hidden boolean not null default false
);

-- Shared real-time-style chat history.
create table public.chat_messages (
    id bigint generated by default as identity primary key,
    profile_auth_subject text not null references public.profiles(auth_subject) on delete cascade,
    content text not null,
    created_at timestamptz not null default timezone('utc', now()),
    is_hidden boolean not null default false
);

-- LunaTicK Talk social posts, comments, and one vote per author/post.
create table public.lunatick_talk_posts (
    id bigint generated by default as identity primary key,
    profile_auth_subject text not null references public.profiles(auth_subject) on delete cascade,
    user_moon_sign text,
    current_moon_phase text,
    content text not null,
    image_path text,
    upvotes integer not null default 0 check (upvotes >= 0),
    downvotes integer not null default 0 check (downvotes >= 0),
    created_at timestamptz not null default timezone('utc', now()),
    is_anonymous boolean not null default true,
    is_hidden boolean not null default false
);

create table public.lunatick_talk_comments (
    id bigint generated by default as identity primary key,
    post_id bigint not null references public.lunatick_talk_posts(id) on delete cascade,
    profile_auth_subject text not null references public.profiles(auth_subject) on delete cascade,
    content text not null,
    upvotes integer not null default 0 check (upvotes >= 0),
    downvotes integer not null default 0 check (downvotes >= 0),
    created_at timestamptz not null default timezone('utc', now()),
    is_anonymous boolean not null default true,
    is_hidden boolean not null default false
);

create table public.user_votes (
    profile_auth_subject text not null references public.profiles(auth_subject) on delete cascade,
    post_id bigint not null references public.lunatick_talk_posts(id) on delete cascade,
    vote_type text not null check (vote_type in ('up', 'down')),
    created_at timestamptz not null default timezone('utc', now()),
    primary key (profile_auth_subject, post_id)
);

-- Cosmic Card exchanges. The status check encodes the approved lifecycle.
create table public.card_trades (
    id bigint generated by default as identity primary key,
    sender_auth_subject text not null references public.profiles(auth_subject) on delete cascade,
    receiver_auth_subject text not null references public.profiles(auth_subject) on delete cascade,
    message text not null default '',
    status text not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'completed', 'cancelled')),
    created_at timestamptz not null default timezone('utc', now()),
    resolved_at timestamptz,
    constraint card_trades_distinct_participants check (sender_auth_subject <> receiver_auth_subject)
);

-- Server-only audit and reconciliation record for every SQLite import run.
create table public.migration_log (
    id bigint generated by default as identity primary key,
    run_id uuid not null,
    stage text not null,
    severity text not null check (severity in ('info', 'warning', 'error')),
    entity text not null,
    source_count bigint,
    target_count bigint,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

-- Required and supporting performance indexes.
create unique index idx_profiles_username on public.profiles (username);
create index idx_journal_profile_phase on public.journal_entries (profile_auth_subject, phase, created_at desc);
create index idx_talk_posts_phase on public.lunatick_talk_posts (current_moon_phase, created_at desc);
create index idx_talk_comments_post_id on public.lunatick_talk_comments (post_id, created_at asc);
create index idx_board_posts_board_created on public.board_posts (board_slug, created_at desc);
create index idx_chat_messages_created on public.chat_messages (created_at desc);
create index idx_card_trades_sender_status on public.card_trades (sender_auth_subject, status);
create index idx_card_trades_receiver_status on public.card_trades (receiver_auth_subject, status);
create index idx_migration_log_run_stage on public.migration_log (run_id, stage, created_at asc);

-- The Phase B access boundary is server-side only. RLS stays enabled even though
-- browser roles have no privileges. Any future direct browser API needs explicit
-- grants and policies in a separate reviewed migration.
alter table public.profiles enable row level security;
alter table public.journal_entries enable row level security;
alter table public.boards enable row level security;
alter table public.board_posts enable row level security;
alter table public.chat_messages enable row level security;
alter table public.lunatick_talk_posts enable row level security;
alter table public.lunatick_talk_comments enable row level security;
alter table public.user_votes enable row level security;
alter table public.card_trades enable row level security;
alter table public.migration_log enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.journal_entries from anon, authenticated;
revoke all on table public.boards from anon, authenticated;
revoke all on table public.board_posts from anon, authenticated;
revoke all on table public.chat_messages from anon, authenticated;
revoke all on table public.lunatick_talk_posts from anon, authenticated;
revoke all on table public.lunatick_talk_comments from anon, authenticated;
revoke all on table public.user_votes from anon, authenticated;
revoke all on table public.card_trades from anon, authenticated;
revoke all on table public.migration_log from anon, authenticated;

revoke all on all sequences in schema public from anon, authenticated;

grant select, insert, update, delete on table public.profiles to service_role;
grant select, insert, update, delete on table public.journal_entries to service_role;
grant select, insert, update, delete on table public.boards to service_role;
grant select, insert, update, delete on table public.board_posts to service_role;
grant select, insert, update, delete on table public.chat_messages to service_role;
grant select, insert, update, delete on table public.lunatick_talk_posts to service_role;
grant select, insert, update, delete on table public.lunatick_talk_comments to service_role;
grant select, insert, update, delete on table public.user_votes to service_role;
grant select, insert, update, delete on table public.card_trades to service_role;
grant select, insert, update, delete on table public.migration_log to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;
