-- LunaTicK Phase G: founder and delegated moderation for public Community content.
--
-- Scope is deliberately limited to Board posts, Chat messages, LunaTicK Talk posts,
-- and LunaTicK Talk comments. Private Journal entries and private profile fields are
-- not referenced by any moderation table or role-management operation.

begin;

create table public.moderator_roles (
    auth_subject text primary key references public.profiles(auth_subject) on delete cascade,
    role text not null check (role in ('founder', 'moderator')),
    is_active boolean not null default true,
    granted_by_auth_subject text references public.profiles(auth_subject) on delete set null,
    granted_at timestamptz not null default timezone('utc', now()),
    revoked_at timestamptz
);

create table public.moderation_actions (
    id bigint generated by default as identity primary key,
    moderator_auth_subject text not null references public.profiles(auth_subject) on delete restrict,
    target_type text not null check (
        target_type in ('board_post', 'chat_message', 'talk_post', 'talk_comment', 'moderator_role')
    ),
    target_id bigint,
    target_auth_subject text references public.profiles(auth_subject) on delete set null,
    action text not null check (action in ('hide', 'restore', 'delete', 'grant_role', 'revoke_role')),
    reason text not null default '',
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    constraint moderation_actions_target_required check (
        target_id is not null or target_auth_subject is not null
    )
);

create index idx_moderator_roles_active on public.moderator_roles (is_active, role);
create index idx_moderation_actions_target on public.moderation_actions (target_type, target_id, created_at desc);
create index idx_moderation_actions_actor on public.moderation_actions (moderator_auth_subject, created_at desc);

alter table public.moderator_roles enable row level security;
alter table public.moderation_actions enable row level security;

revoke all on table public.moderator_roles from anon, authenticated;
revoke all on table public.moderation_actions from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

grant select, insert, update, delete on table public.moderator_roles to service_role;
grant select, insert, update, delete on table public.moderation_actions to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;
