-- Owner-only Track entries: general personal date notes and optional observed
-- cycle markers. No browser role may access this table directly.
begin;

create table public.calendar_entries (
    id bigint generated by default as identity primary key,
    profile_auth_subject text not null references public.profiles(auth_subject) on delete cascade,
    entry_date date not null,
    note text not null default '' check (char_length(note) <= 2000),
    cycle_marker text check (cycle_marker in ('started', 'ended') or cycle_marker is null),
    severity integer check (severity between 1 and 5 or severity is null),
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (profile_auth_subject, entry_date)
);

create index idx_calendar_entries_profile_date
    on public.calendar_entries (profile_auth_subject, entry_date asc);

alter table public.calendar_entries enable row level security;
revoke all on table public.calendar_entries from anon, authenticated;
revoke all on sequence public.calendar_entries_id_seq from anon, authenticated;
grant select, insert, update, delete on table public.calendar_entries to service_role;
grant usage, select on sequence public.calendar_entries_id_seq to service_role;

create policy server_only_calendar_entries on public.calendar_entries
    for all to anon, authenticated
    using (false)
    with check (false);

commit;
