-- Free community Reading Requests with private matched conversations.

create table if not exists public.reading_readers (
    profile_auth_subject text primary key references public.profiles(auth_subject) on delete cascade,
    display_name text not null,
    avatar text not null default '🌙',
    focus text not null default '',
    intro text not null default '',
    is_available boolean not null default false,
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.reading_requests (
    id bigint generated by default as identity primary key,
    requester_auth_subject text not null references public.profiles(auth_subject) on delete cascade,
    requester_name text not null,
    topic text not null,
    private_context text not null default '',
    status text not null default 'open' check (status in ('open', 'matched', 'closed', 'cancelled')),
    reader_auth_subject text references public.profiles(auth_subject) on delete set null,
    reader_name text,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.reading_messages (
    id bigint generated by default as identity primary key,
    reading_request_id bigint not null references public.reading_requests(id) on delete cascade,
    sender_auth_subject text not null references public.profiles(auth_subject) on delete cascade,
    sender_name text not null,
    content text not null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_reading_readers_available on public.reading_readers(is_available, updated_at desc);
create index if not exists idx_reading_requests_open on public.reading_requests(status, created_at desc);
create index if not exists idx_reading_requests_members on public.reading_requests(requester_auth_subject, reader_auth_subject, updated_at desc);
create index if not exists idx_reading_messages_request on public.reading_messages(reading_request_id, created_at asc);

alter table public.reading_readers enable row level security;
alter table public.reading_requests enable row level security;
alter table public.reading_messages enable row level security;

revoke all on table public.reading_readers, public.reading_requests, public.reading_messages from anon, authenticated;
grant select, insert, update, delete on table public.reading_readers, public.reading_requests, public.reading_messages to service_role;

create policy server_only_reading_readers on public.reading_readers for all to service_role using (true) with check (true);
create policy server_only_reading_requests on public.reading_requests for all to service_role using (true) with check (true);
create policy server_only_reading_messages on public.reading_messages for all to service_role using (true) with check (true);
