-- Connection-gated member-to-member Profile Direct Messages.
-- The Streamlit server uses the service role and rechecks accepted card trades
-- before every thread open, read, and write. Browser roles receive no access.

create table if not exists public.direct_message_threads (
    id bigint generated by default as identity primary key,
    participant_one_auth_subject text not null references public.profiles(auth_subject) on delete cascade,
    participant_two_auth_subject text not null references public.profiles(auth_subject) on delete cascade,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    constraint direct_message_threads_distinct_participants
        check (participant_one_auth_subject <> participant_two_auth_subject),
    constraint direct_message_threads_canonical_pair
        check (participant_one_auth_subject < participant_two_auth_subject),
    constraint direct_message_threads_unique_pair
        unique (participant_one_auth_subject, participant_two_auth_subject)
);

create table if not exists public.direct_messages (
    id bigint generated by default as identity primary key,
    thread_id bigint not null references public.direct_message_threads(id) on delete cascade,
    sender_auth_subject text not null references public.profiles(auth_subject) on delete cascade,
    sender_name text not null,
    content text not null check (char_length(content) between 1 and 1200),
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_direct_message_threads_one
    on public.direct_message_threads(participant_one_auth_subject, updated_at desc);
create index if not exists idx_direct_message_threads_two
    on public.direct_message_threads(participant_two_auth_subject, updated_at desc);
create index if not exists idx_direct_messages_thread
    on public.direct_messages(thread_id, created_at asc);

alter table public.direct_message_threads enable row level security;
alter table public.direct_messages enable row level security;

revoke all on table public.direct_message_threads, public.direct_messages from anon, authenticated;
grant select, insert, update, delete on table public.direct_message_threads, public.direct_messages to service_role;

create policy server_only_direct_message_threads on public.direct_message_threads
    for all to service_role using (true) with check (true);
create policy server_only_direct_messages on public.direct_messages
    for all to service_role using (true) with check (true);
